### ISSUE TITLE
Cambio segmentación de fechas

### ISSUE THREAD

**Issue by mstadeo** [mstadeo/segvial#1]
Ingresar manualmente la fecha de inicio y fin para segmentar los datos. Sería un cambi en esta [linea](https://github.com/mstadeo/segvial/blob/f34c4d7cd539933c14085440101e05f8029af0c6/streamlit_app.py#L29).

**Comment by mstadeo** [comment]
@ccandeci listar los filtros que necesitan

**Comment by abrilr1604** [comment]
@mstadeo sol, el slider quedó en la última actualización que hice. Al final, lo dejo o pongo la opción para ingresar manualmente la fecha de inicio y fin? (creo que aparece un mini calendario en cada uno)

Otra cosa, el slider actualmente sólo modifica el mapa del principio, donde se muestran los siniestros. ¿Hago que también modifique los gráficos que le siguen? Porque para algunos no tendría sentido dependiendo lo que ingrese el usuario, por ejemplo los involucrados por año, los involucrados por mes, la cantidad de siniestros por año...

**Comment by msoltadeo** [comment]
Al final, el filtro filtra todos los gráficos
