### ISSUE TITLE
Total de heridos por tipo de herido por año

### ISSUE THREAD

**Issue by mstadeo** [mstadeo/segvial#10]
@abrilr1604 necesitamos hacer de este gráfico uno solo. Queremos ver la cantidad total de involucrados por tipo de gravedad por año. No están interesados en los ilesos, por lo tanto vamos a tener 4 categorías: `heridos leves, heridos graves, heridos gravisimos y fallecidos`
El código a cambiar es este que está acá
https://github.com/mstadeo/segvial/blob/dab7c58e6098f6295040fbb6cdf9700495445786/streamlit_app.py#L90-L98

**Comment by abrilr1604** [comment]
@mstadeo Buenas! Cambié el código y estos fueron los resultados:

![image](https://github.com/mstadeo/segvial/assets/110438392/40b91cd3-70df-4ac9-9cd9-bf032d686e23)

Como se ve,  a simple vista se aprecian muy poco los heridos graves, gravísimos y fallecidos porque hay una gran cantidad de personas con heridas leves. Por ejemplo, para el 2012 los heridos leves son aproximadamente 9500, mientras que los heridos gravísimos son 14 y hay que visualizarlos haciendo zoom en la imagen.

Código actualizado:

```
fig = px.bar(anios_interes, x = 'anio',  y = ['heridos_leves', 'heridos_graves', 'heridos_gravisimos', 'fallecidos' ], barmode = 'group',  
              labels = {'anio': 'Año', 'value': 'Cantidad de involucrados'},  
              title = 'Tipo de gravedad de los involucrados por Año')
fig.update_layout(legend_title='Tipo de gravedad') 
fig.for_each_trace(lambda t: t.update(name='Heridos leves' if t.name == 'heridos_leves' else
                                             'Heridos graves' if t.name == 'heridos_graves' else
                                             'Heridos gravísimos' if t.name == 'heridos_gravisimos' else
                                             'Fallecidos'))
columns[1].plotly_chart(fig) 
```

**Comment by mstadeo** [comment]
@abrilr1604
Te doy dos opciones para que se vea mejor
1. Agregar un botón para quitar a los heridos leves del gráfico. Si seguís esta opción, fijate de filtar en un df auxiliar para que no te filtre todos los datos
2. Generar 2 gráficos, uno con y otro sin heridos leves.

**Comment by abrilr1604** [comment]
@mstadeo hola sol! me pareció que la mejor idea era incluir un botón para  no sobrecargar mucho la página con gráficos del mismo tema, pero el problema (para mí, pero es gusto personal de diseño) es que quería que el botón se encuentre en medio del título del gráfico y el gráfico, pero no lo pude hacer funcionar. lo googlé y creo que es posible con html, probé un código que encontré pero directamente no me mostraba el gráfico.
Lo máximo que puedo hacer es que quede por encima del gráfico entero o por debajo. 

Por otro lado, como se ve, el gráfico no queda alineado con el de la izquierda, pero estoy esperando a tener una plantilla organizada de cómo quieren que se vea la página para ver todos esos temas de diseño y dejarlo prolijo.

![image](https://github.com/mstadeo/segvial/assets/110438392/4e6eb8f1-cf1d-4e52-b741-1eca20ef7506)

Igual, si para el resultado final se desea tener dos gráficos, uno donde se vean los heridos leves y otro donde no, no hay ningún problema en agregarlo, es muy sencillo.

**Comment by msoltadeo** [comment]
@abrilr1604 estoy de acuerdo con mirar los temas de diseño cuando ya tengamos la plantilla completa. Cerra el issue cuando tengas la PR de esto mergeada.
