### ISSUE TITLE
Participación por modo

### ISSUE THREAD

**Issue by mstadeo** [mstadeo/segvial#11]
Generar un gráfico que nos muestre la participación por modos en los accidentes. 
El resultado debería informarnos algo así como:
En el 30% de los accidentes hubo motos involucradas
En el 90% de los accidentes hubo autos involucrados

Hay que tener en cuenta que la suma no es 100, va a ser mayor ya que en un mismo accidente intervienen varios modos.
@abrilr1604

**Comment by abrilr1604** [comment]
@mstadeo hola Sol! no termino de entender bien la lógica a aplicar para este issue. Por lo que entendí al principio, el porcentaje se calcula sobre la cantidad total de accidentes, pero qué sucede con aquellos en donde hay más de un mismo medio de transporte involucrado? (ej, un accidente entre 2 o más autos) 

Lo pensé para un caso pequeño de una base de datos con 4 accidentes, en donde en total hubo 2 autos involucrados. Suponiendo quela participación de esos 2 autos ocurrió en un mismo accidente (lo que sucede en la mayoría de los casos), entonces sería erróneo decir que en el 50% de los accidentes están involucrados los autos, porque eso sería equivalente a decir que hubo participación de autos en 2 de los 4 accidentes. Por otro lado, sí tendría sentido calcular sobre el total de medios de transporte involucrados en todos los accidentes, no? 

Me parece que distinto sería si calculamos el porcentaje de autos, motos, etc. involucrados sobre el total de medios de transporte involucrados en los accidentes, porque ahí sí tiene sentido calcular un porcentaje. Ejemplo: de la totalidad de medios de transporte involucrados en accidentes, el 40% son autos. 

Pero, si queremos calcular el porcentaje de autos sobre la cantidad total de accidentes, me parece que deberíamos tener en cuenta "al menos 1 auto" y no sumar la cantidad de autos en el caso de que haya más de uno. En ese caso, la interpretación sería "de la totalidad de accidentes, en el 60% se vieron involucrados al menos un auto".

Si es como esto último, la lógica a aplicar sería hacer un dataframe de dummies (en donde no importa si se involucraron 2 o más autos, el valor en la columna "auto" valdrá 1) y calcular el porcentaje sobre el total con el siguiente código:
```
transportes = intersecciones_geocod['desc_participante'].str.get_dummies(',')
conteo_transportes = transportes.sum()
porcentaje_transportes = (conteo_transportes / len(intersecciones_geocod)) * 100  
```
Los gráficos que hice fueron los siguiente:
![image](https://github.com/mstadeo/segvial/assets/110438392/37101dd0-32a2-4289-9c6c-a276e959f6de)
![image](https://github.com/mstadeo/segvial/assets/110438392/e3bde680-dd94-4db7-a577-4a56f10d0844)

Por último, si nos interesara calcular el porcentaje de cada medio de transporte involucrado respecto al total de medios de transporte en todos los accidentes, ahí si podría sumar todos los transportes de todos los accidentes sin importar si en un mismo accidente hubo más de un mismo medio de transporte involucrado. 
El código a utilizar sería el siguiente:
```
transportes = data['desc_participante'].str.split(',', expand=True)
conteo_transportes = transportes.stack().value_counts()  # cuento numero de ocurrencias de cada vehículo
porcentaje_transportes = (conteo_transportes / conteo_transportes.sum() * 100).round(2)   # calculo porcentaje
```
Y para este caso sí tendría sentido hacer un gráfico de torta, ya que la suma da 100. 

![image](https://github.com/mstadeo/segvial/assets/110438392/0058713e-9809-4713-a0b4-e419cc2e0fe8)

PD: hice dos gráficos de barras para probar, uno de barras verticales y otro de horizontales. En el de horizontales, se facilita pasar el mouse por encima de las barras, el punto malo que le veo es que no queda muy lindo porque hay medios de transporte que tienen nombres bastante más largos que los demás.
Además, tuve que agrandar bastante el gráfico respecto a los demás porque hay muchos medios de transporte y no se visualiza entero en la pantalla. 

Por otro lado, el gráfico de barras verticales se visualiza entero en la pantalla, pero se tuvieron que rotar los nombres de los transportes porque se dificultaba leerlos. Además, se complica bastante pasar el mouse por las barras pequeñas sin hacer zoom en el gráfico.

**Comment by mstadeo** [comment]
@abrilr1604 , gracias por el análisis, muy buenos tus puntos.

A mi me gustaría ver esto:
>Si es como esto último, la lógica a aplicar sería hacer un dataframe de dummies (en donde no importa si se involucraron 2 o más autos, el valor en la columna "auto" valdrá 1) y calcular el porcentaje sobre el total con el siguiente código:

Los modos que tienen una participación baja podemos agruparlos dentro de una categoría que se llame `otros`. De esa forma, el gráfico se va a apreciar mejor. 

Con respecto a esto:
>Por último, si nos interesara calcular el porcentaje de cada medio de transporte involucrado respecto al total de medios de transporte en todos los accidentes, ahí si podría sumar todos los transportes de todos los accidentes sin importar si en un mismo accidente hubo más de un mismo medio de transporte involucrado.
El código a utilizar sería el siguiente:

Que @ccandeci @aleglk nos digan cuál prefieren ellas. Tal vez hay alguna razón para preferir el segundo.

**Comment by abrilr1604** [comment]
@mstadeo decidí agrupar:
-  ['Transporte de Pasajeros', 'Transporte de Pasajeros (H/ 8 asientos)', 'Transporte de Pasajeros Larga Distancia (> 8 asientos)',  'Transporte de Pasajeros Larga Distancia (Doble Piso)','Transporte de Pasajeros Larga Distancia (Piso  y  1/2)', 'Transporte de Pasajeros Urbano (> 8 asientos)'] en **['Transporte de Pasajeros']**
- ['Camión','Camión Chasis','Camión c / Acoplado','Camión c / Semirremolque'] en **['Camión']**

porque ya existe la categoría 'Otros' en la bbdd (no se bien a qué medios de transporte se referirá)
El resultado es el siguiente:

![image](https://github.com/mstadeo/segvial/assets/110438392/77b074a6-29c3-45ea-ab8d-6870d7edd471)

Si prefieren que sea en barras horizontales, quedaría así
![image](https://github.com/mstadeo/segvial/assets/110438392/347780c0-b13a-455a-9cad-5afd6a91ea33)

PD: no sabía si también agregar 'Transporte Escolar' en 'Transporte de Pasajeros'. 
Se sigue dificultando pasar el mouse por encima de las barras pequeñas. Cualquier cosa, hice otro gráfico con los porcentajes al lado de las barras. Si lo prefieren así, elimino los otros.

![image](https://github.com/mstadeo/segvial/assets/110438392/7b665b27-3b6c-4eec-99f6-127dcd44f6e3)

Entonces, para cerrar el issue, quedaría que me confirmen si prefieren gráfico de barras horizontal o vertical, si les parece correcto la agrupación de transporte de pasajeros y camión o si prefieren que se vean todas las categorías, y si desean que se vean los porcentajes o no.

**Comment by ccandeci** [comment]
Hola chicas! Como estan? Les respondemos a sus consultas.
En primer lugar nos parece mas legible el gráfico de barras, lo que si haríamos sería un recorte de información, cuando la categoría no llega a 1% no debería de visualizarse en el gráfico. Si agregaríamos (en medida que sea posible) un llamado haciendo referencia a que hay valores que no se encuentran visibles en el gráfico, cuales son y cual su porcentaje. Esto sería con el fin de que no "ensucie" el gráfico pero que tampoco se pierda información. 
Si preferimos que se visualicen los % de cada modo en el gráfico.
En cuanto a la división de modos opinamos de la misma manera por lo cual esta correcta.
Por último quisieramos recordarles que cuando hablamos de sucesos son "Siniestros" no "Accidentes" y los involucrados son "Modos" no "Medios" por lo cual necesitaríamos cambiar esas palabras en los gráficos.

**Comment by msoltadeo** [comment]
@ccandeci gracias por tus comentarios. 
@abrilr1604, decinos si lo que plantea cande es posible de hacer.

**Comment by abrilr1604** [comment]
@msoltadeo perfecto, ya filtré el gráfico de barras para que sólo muestre los modos con porcentaje mayor al 1%. En cuanto a dejar anotado los modos que no alcanzaron el 1%, sólo se me ocurrió escribirlos al lado del gráfico. No estoy segura si hay alguna otra manera de que quede prolijo, pero si se les ocurre me dicen (lo mismo si quieren cambiar el texto, su formato etc.)

![image](https://github.com/mstadeo/segvial/assets/110438392/95a7170d-e484-4c11-90a2-efe98866b26b)

**Comment by mstadeo** [comment]
@abrilr1604, vamos a hacar una aclaración sobre los títulos para que se entienda bien. Vamos a agregar el grafico que muestra el % de modos sobre el total de modos.
