### ISSUE TITLE
Segmentación días de semana

### ISSUE THREAD

**Issue by mstadeo** [mstadeo/segvial#12]
@abrilr1604 neceistamos 2 gráficos de barras:
1. que muestre la cantidad de siniestros por día de la semana 
2. que muestra la cantidad de sienistros para la semana y para el fin de semana

Abajo te dejo el ejemplo de lo que queremos mostrar. Te dejo a vos para que elijas como hacerlo. 
![image](https://github.com/mstadeo/segvial/assets/102703859/e03723ae-1473-4719-a38f-68379cb93cd8)

**Comment by abrilr1604** [comment]
@mstadeo hola sol! para representar la distribución de accidentes ocurridos en día de semana y fin de semana, hice este gráfico de barras. también agregué un gráfico de torta, por las dudas, por si se quiere representar un porcentaje. 

![image](https://github.com/mstadeo/segvial/assets/110438392/f49bb294-64bf-4d6b-b826-6900959372dc)

después, quise hacer en un mismo gráfico la comparación entre los días de semana de lunes a viernes y fin de semana (como otra categoría), pero tenía problemas con plotly porque no me ponía pegadas una al lado de la otra las barras del fin de semana (sábado y domingo) y me dejaba un espacio entre los días de semana.

Entonces tuve que hacer los gráficos por separado:
![image](https://github.com/mstadeo/segvial/assets/110438392/9d3d56df-3cd6-4ec5-bd03-4a37851440ab)

de todas formas si prefieren el gráfico todo junto, puedo seguir intentando para ver si me deja, porque me separa las barras así y no sé por qué:

![image](https://github.com/mstadeo/segvial/assets/110438392/968b5b84-2f0d-40ef-8da1-9ba5e8ccc496)

**Comment by msoltadeo** [comment]
@abrilr1604, para el segundo gráfico, siniestro por día de la semana, te sugiero que uses día de la semana, sin clasificar. Es decir, el eje x va a ser `Lunes, Martes, Miercoles, Jueves, Viernes, Sábado, Domingo`. Lo interesante de estoes ver si algún día captura un mayor porcentaje de accidentes, pero a simple vista, parece que no. Te parece? 

En cuanto al primer gráfico está OK.

**Comment by abrilr1604** [comment]
@msoltadeo perfecto, así quedo el gráfico de barras con todos los días de la semana:

![image](https://github.com/mstadeo/segvial/assets/110438392/98d6f9da-d48a-4521-a21c-a93bbb62c84c)

agregué el numero de siniestros arriba de cada barra, pero cualquier cosa se saca. También forcé que los días aparezcan en orden,  porque sino se muestran de mayor a menor según la cantidad de siniestros

**Comment by msoltadeo** [comment]
@abrilr1604 me gusta mucho :heart_eyes: . Cuando puedas hace la PR y agregame como revisora :muscle:
