### ISSUE TITLE
Segmentación por tipo de calzada

### ISSUE THREAD

**Issue by mstadeo** [mstadeo/segvial#13]
@abrilr1604 necesitamos mostrar un gráfico de sieniestros por tipo de calzada.

**Comment by abrilr1604** [comment]
@mstadeo hice un gráfico de barras y uno de torta para representar los porcentajes, cuando puedas decime qué te parece

![image](https://github.com/mstadeo/segvial/assets/110438392/ab0bfaf5-9e9a-4a84-af1c-b8f48996eadb)

**Comment by msoltadeo** [comment]
@abrilr1604 , el gráfico de torta me gusta más.
