### ISSUE TITLE
Mapa con horario del evento

### ISSUE THREAD

**Issue by mstadeo** [mstadeo/segvial#18]
@ccandeci podrías pasarnos el ejemplo para que hagamos el mapa con los puntos con colores según a qué hora ocurrió el evento?

**Comment by ccandeci** [comment]
![image](https://github.com/mstadeo/segvial/assets/161733292/fbf26606-254a-4807-8c5c-534454b2bdc3)

**Comment by abrilr1604** [comment]
@mstadeo @ccandeci hola, buenas  noches!! les muestro como quedó el gráfico en Streamlit:
 
![image](https://github.com/mstadeo/segvial/assets/110438392/fd2cf1cc-a5e8-4837-9259-792ed27f9a66)

No pude hacer que se muestre el contorno del mapa de rosario (sólo me deja hacerlo interactivo) , como sí pude con matplotlib:

![image](https://github.com/mstadeo/segvial/assets/110438392/0f443b3e-5d12-449e-9a23-41901aaaff46)

El problema que veo en usar matplotlib es que todos los demás gráficos los hice con plotly, que queda mucho más lindo y se puede pasar el mouse por encima y ver alguna descripción de los datos. 

Por otro lado, un problema al hacer el mapa interactivo con plotly es que también hay siniestros que se geocodificaron en otras ciudades, y no sé como filtrarlos. Tendría que ver si se pueden filtrar teniendo en cuenta el contorno del mapa, pero no estoy segura. Lo mismo con los gráficos anteriores, me tengo que fijar si puedo filtrar por fuera del contorno.

**Comment by ccandeci** [comment]
Hola!! Charlando con las chicas nos pareció mejor que quede el primero en la página. Cualquier cosa nos consultan

**Comment by abrilr1604** [comment]
genial! ya está agregado. Apenas tenga terminada la página de calidad de datos actualizo el script en el repo así Sol le da el ok a la PR :)
