### ISSUE TITLE
Filtrar siniestros fuera de Rosario

### ISSUE THREAD

**Issue by abrilr1604** [mstadeo/segvial#21]
@msoltadeo sol cuando puedas, podrías pasarme el código que hablamos en la última reunión para filtrar todos los siniestros que no son de Rosario? La idea era que no se vean en el mapa del Streamlit. 

Por último, confírmame si además de eso y cambiar el slider por ingresar las fechas de interés en formato calendario no faltaría nada más para terminar la electiva

**Comment by msoltadeo** [comment]
@abrilr1604 el código sería algo asi:
1. Cargas todos los datos que tenes
2. Cargas la capa georeferenciada con todos los municipios. No recuerdo si ya lo tenes filtrado por Rosario o no
3. Si en 2 cargaste todos los municipios, quedate solo con Rosario ahora. 
4. Vas a hacer una union espacial (spatial join o sjoin). Viste que en BBDD unís dos tablas usando una columna en común. Acá, en lugar de usar una columna para unir los datos se usa la localización. La idea es poder detectar todos los puntos que "caen dentro de"/se intersectan con los límites de Rosario. Cuando hagas la unión espacial vas a ver que el nuevo gdf tiene las columnas del df data y del df municipio_rosario. Los puntos que NO están en Rosario son aquellos para los cuales las columnas de municipio_rosario tienen valores nulos.
```
data = los datos de siniestros
municipios = cargas los municipios
municipio_rosario = filtras municipios y te quedas solo con los de rosario
sjoin = gpd.sjoin(data, municipio, how = 'left', predicate = 'intersects'
sjoin = filtras solo los registros que hayan tomado el valor de rosario
```
Sin embargo, me parece que no solo lo tendrías que filtrar para mostrar en el mapa, sino para todo, no?

Cualquier duda escribime!

**Comment by abrilr1604** [comment]
@msoltadeo funcionó! sí, tengo que filtrarlo para todo. Yo ahora estoy armando el geodataframe y filtrando los siniestros directamente en el script de streamlit y de la página de calidad de datos, pero eso requiere leer el gpkg de los municipios de Santa Fe, filtrar Rosario, armar un geodataframe del csv, y hacer el sjoin. 

No sé si convendría ejecutar nuevamente la notebook de las geocodificaciones y guardarme el geodataframe final con los siniestros de Rosario para trabajar con ese archivo en Streamlit (yo hasta ahora estuve usando el csv excepto para armar el mapa).  Si sirve, lo vuelvo a ejecutar y lo subo al repositorio, quedaría el csv y el geodataframe. No sé qué opinas?

**Comment by msoltadeo** [comment]
@abrilr1604, lo mejor sería que filtres lo antes posible, es decir, en la notebook de geocodificación. Pero no es necesario que corras toda la geocodificación otra vez, tomas el ultimo archivo, lo cargas y lo filtras. 

Se entiende?

**Comment by abrilr1604** [comment]
@msoltadeo tal cual, no me di cuenta! apenas tenga todo (espero mañana) hago la PR. Agrego el geodataframe al repo, actualizo el streamlit que cambia el slider y los datos filtrados y actualizo la notebook de geocodificaciones con el filtrado al final.

**Comment by abrilr1604** [comment]
@msoltadeo hola sol! ya modifiqué el archivo de geocodificaciones, al final guardé el geodataframe como csv, así ya queda en el repo reemplazado por el anterior. 

En cuanto al Streamlit, ya modifiqué el slider por el widget de calendario y filtra bien los datos.

![image](https://github.com/mstadeo/segvial/assets/110438392/3eb7d386-6958-4acc-ae36-c94145ca3bae)

La idea es que no solo filtre los datos del mapa, sino también los de los demás gráficos. El tema es, como te mencioné en una de las últimas reuniones, hay algunos que no tendrían sentido, dependiendo del rango de fechas que se seleccione. Por ejemplo, yo seleccioné el rango 2012/01/01 - 2012/02/01 (un mes de diferencia) y los primeros gráficos, al menos el primero, no tienen sentido.

![image](https://github.com/mstadeo/segvial/assets/110438392/195ff8e9-485a-4185-a4a0-a338b3286dfe)

Los dos siguientes también quedan medio raros. Sobre todo el de la izquierda, que muestra una única barra.
![image](https://github.com/mstadeo/segvial/assets/110438392/924defa1-8fed-4339-b0aa-9622c5e45b66)

Los demás ya están modificados y no tienen problema. No se si para esos gráficos que no tienen sentido, quedaría mejor dejarlos como estaban, abarcando todos los datos o los dejo como están. 

Una última cuestión, en la página de 'Calidad de datos' yo uso el dataframe sin modificar 'data_final.csv' porque representan los datos antes de realizar todo el procesamiento, a excepción de la última sección donde muestro un gráfico de barras sobre los resultados de las geocodificaciones ('geocodificado', 'error', 'ppal calles no encontradas', 'sec calles no encontradas', 'ambas calles no encontradas'). Esto está bien no? Aunque en las primeras secciones figuren siniestros que no son de Rosario y estén categorizados como tal? o prefieren que use el dataframe ya procesado en toda la página de calidad de datos?

Cuando esté solucionado esto, hago la PR!

**Comment by msoltadeo** [comment]
@abrilr1604 Yo prefiero que filtres todo, para que sea consistente. 
>Los dos siguientes también quedan medio raros. Sobre todo el de la izquierda, que muestra una única barra.

Es verdad que se ve raro, pero es entendible por como se filtraron los datos.

Para la página de calidad de datos, prefiero que usemos los datos en crudo/raw porque el IET usa esa página para tener una idea general

**Comment by abrilr1604** [comment]
@msoltadeo listo!! ya hice una PR con los nuevos cambios. Aclaro por las dudas, que no entiendo por qué aparece un espacio grande vacío abajo del mapa en la app de streamlit, antes de los gráficos. Esto se soluciona cuando selecciono un rango de fechas, pero capaz es porque lo corro local, no encontré ningún error en el código.
