### ISSUE TITLE
Agregar titulos, nombres en los ejes y unidades a los gráficos

### ISSUE THREAD

**Issue by mstadeo** [mstadeo/segvial#3]

**Comment by abrilr1604** [comment]
@mstadeo Hecho! Tengo un par de dudas sobre algunos gráficos porque no sé que criterio utilizan a la hora de determinar el título o los nombres de los ejes y unidades, pero cualquier cosa que se necesite cambiar es muy sencillo de hacer así que no hay ningún problema. 
Por ejemplo, para los ejes, consideran el nombre de la variable + la unidad en el caso de la fecha? ¿'Año' y 'Mes' o 'Fecha (año)' y 'Fecha (mes)'?

**Comment by mstadeo** [comment]
@abrilr1604, perfecto. Cerramos el issue cuando esté mergeada la PR
