### ISSUE TITLE
Boton para filtrar los ilesos

### ISSUE THREAD

**Issue by mstadeo** [mstadeo/segvial#4]
Generar un botón general, para ambas pantallas, para eliminar los registros que tienen solamente ilesos.
`data[(data['ilesos']>0) & (data['total_heridos_fallecidos']==0)]`

**Comment by mstadeo** [comment]
El botón debería ir después de[ esta línea ](https://github.com/mstadeo/segvial/blob/dab7c58e6098f6295040fbb6cdf9700495445786/streamlit_app.py#L19)
Debería llamarse "eliminar siniestros que no tuvieron heridos ni fallecidos"

**Comment by abrilr1604** [comment]
@mstadeo  listo!
El botón quedó al principio de la página, pero cualquier cosa sobre el diseño del streamlit q surja más adelante se cambia sin problema.  
 
![image](https://github.com/mstadeo/segvial/assets/110438392/726a432d-7117-48e4-83a5-659ec9ffd2ee)

el código que agregué fue el siguiente:

```
# BOTON FILTRAR ILESOS
boton_sin_ilesos = st.checkbox("Eliminar siniestros sin heridos ni fallecidos")

data['total_heridos_fallecidos'] = data['heridos_leves'] + data['heridos_graves'] + data['heridos_gravisimos'] + data['fallecidos']

if boton_sin_ilesos:
    data = data.loc[(data['ilesos'] == 0) | (data['total_heridos_fallecidos'] > 0)] # filtro para obtener donde haya ilesos y no haya ningun herido ni fallecido. SOLO ILESOS
```
